FROM python:3.6.4

RUN mkdir /app
WORKDIR /app

USER root
RUN apt update && apt install -y poppler-utils

# INSTALL DEPENDENCIES
COPY requirements.txt /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8080
