FROM python:3.6.4

RUN mkdir /app
WORKDIR /app

USER root
RUN apt update && apt install -y poppler-utils

# INSTALL DEPENDENCIES
COPY requirements.txt /app
COPY requirements-dev.txt /app
RUN pip install -r requirements-dev.txt

EXPOSE 8080
